### ISSUE TITLE
2023_OlaldeCarrion_Roman

### ISSUE THREAD

**Issue by danimfernandes** [poseidon-framework/minotaur-recipes#12]
## Check for existing package

I have checked the following places for the requested package and could not find
it:

- [x] Poseidon Minotaur Archive
- [x] The `packages/` directory in this repository
- [x] Open issues in this repository
- [x] Open pull requests in this repository

## Required information for the package

- DOI of publication: [https://doi.org/10.1016/j.cell.2023.10.018](https://doi-org.offsitelib.eva.mpg.de/10.1016/j.cell.2023.10.018)
- Project accession number: [PRJEB66422](https://www.ebi.ac.uk/ena/data/view/PRJEB66422)

## Will you work on this?
Yes, I have the SSF file ready.

**Comment by stschiff** [comment]
I keep forgetting, @TCLamnidis, but didn't we consider leaving these issues open until the package has actually been added to the archive? I see why you want to close it once the recipe gets merged, but then what was our plan on how to indicate to the user that a particular package is in fact currently being processed? I remember we discussed that we wanted to have that reflected on GitHub somehow, through open PRs or issues on either `minotaur-recipes` or `minotaur-archives`
